root = "."
tmp_dir = "tmp"

[build]
cmd = 'go build -gcflags "all=-N -l" -o ./tmp/app ./cmd/app.go'
full_bin = "dlv --listen=127.0.0.1:2345 --headless=true --api-version=2 --accept-multiclient exec --continue tmp/app"
