version: '3'
services:
  go-sandbox:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    command:
      - air
      - -c
      - .air.toml
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - 8080:5000
      - 2345:2345
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    networks:
      - sandbox_network
  cassandra:
    image: cassandra:4.0
    tty: true
    ports:
      - 9042:9042
    networks:
      - sandbox_network

networks:
  sandbox_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
