name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check lint
        run: make lint

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: build test
      run: make      

  test:
    needs: [build]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: make test
