name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          # go 1.17 だと golangci-lint が error になる
          # https://github.com/golangci/golangci-lint/issues/2292
          go-version: 1.16
      - name: check lint
        run: make lint
      - name: check imports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          DIFF=$(goimports -l .)
          if [ ! -z "$DIFF"] then
            echo "failed to check goimports. diff: [$DIFF]"
            exit 1
          fi

  build:
    needs: [lint]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: build test
      run: make      

  test:
    needs: [build]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: test
      run: make test
